#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LMS")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LMS_2.Properties.Settings.Default.LMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectAllBooks")]
		public ISingleResult<selectAllBooksResult> selectAllBooks()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<selectAllBooksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectBookById")]
		public ISingleResult<selectBookByIdResult> selectBookById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> book_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), book_id);
			return ((ISingleResult<selectBookByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertNewBook")]
		public int insertNewBook([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(225)")] string bTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(225)")] string bAuthor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> bPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string bAvailable, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bPublisherId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bTitle, bAuthor, bPrice, bAvailable, bPublisherId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteBookById")]
		public int deleteBookById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> book_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), book_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectAllPublishers")]
		public ISingleResult<selectAllPublishersResult> selectAllPublishers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<selectAllPublishersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectPublisherById")]
		public ISingleResult<selectPublisherByIdResult> selectPublisherById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> publisher_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publisher_id);
			return ((ISingleResult<selectPublisherByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertNewPublisher")]
		public int insertNewPublisher([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(225)")] string pName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PAddress", DbType="VarChar(225)")] string pAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pName, pAddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deletePublisherById")]
		public int deletePublisherById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PId", DbType="Int")] System.Nullable<int> pId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteMemberById")]
		public int deleteMemberById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MId", DbType="Int")] System.Nullable<int> mId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectAllMembers")]
		public ISingleResult<selectAllMembersResult> selectAllMembers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<selectAllMembersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectMemberById")]
		public ISingleResult<selectMemberByIdResult> selectMemberById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> member_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), member_id);
			return ((ISingleResult<selectMemberByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertNewMember")]
		public int insertNewMember([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MName", DbType="VarChar(225)")] string mName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAddress", DbType="VarChar(225)")] string mAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSubscribeDate", DbType="Date")] System.Nullable<System.DateTime> mSubscribeDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MExpiryDate", DbType="Date")] System.Nullable<System.DateTime> mExpiryDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mName, mAddress, mSubscribeDate, mExpiryDate);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class selectAllBooksResult
	{
		
		private int _book_id;
		
		private string _title;
		
		private string _author;
		
		private System.Nullable<double> _price;
		
		private string _available;
		
		private System.Nullable<int> _publisher_id;
		
		public selectAllBooksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_id", DbType="Int NOT NULL")]
		public int book_id
		{
			get
			{
				return this._book_id;
			}
			set
			{
				if ((this._book_id != value))
				{
					this._book_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="VarChar(255)")]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this._author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_available", DbType="VarChar(25)")]
		public string available
		{
			get
			{
				return this._available;
			}
			set
			{
				if ((this._available != value))
				{
					this._available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publisher_id", DbType="Int")]
		public System.Nullable<int> publisher_id
		{
			get
			{
				return this._publisher_id;
			}
			set
			{
				if ((this._publisher_id != value))
				{
					this._publisher_id = value;
				}
			}
		}
	}
	
	public partial class selectBookByIdResult
	{
		
		private int _book_id;
		
		private string _title;
		
		private string _author;
		
		private System.Nullable<double> _price;
		
		private string _available;
		
		private System.Nullable<int> _publisher_id;
		
		public selectBookByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_id", DbType="Int NOT NULL")]
		public int book_id
		{
			get
			{
				return this._book_id;
			}
			set
			{
				if ((this._book_id != value))
				{
					this._book_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="VarChar(255)")]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this._author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_available", DbType="VarChar(25)")]
		public string available
		{
			get
			{
				return this._available;
			}
			set
			{
				if ((this._available != value))
				{
					this._available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publisher_id", DbType="Int")]
		public System.Nullable<int> publisher_id
		{
			get
			{
				return this._publisher_id;
			}
			set
			{
				if ((this._publisher_id != value))
				{
					this._publisher_id = value;
				}
			}
		}
	}
	
	public partial class selectAllPublishersResult
	{
		
		private int _pub_id;
		
		private string _pub_name;
		
		private string _pub_address;
		
		public selectAllPublishersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pub_id", DbType="Int NOT NULL")]
		public int pub_id
		{
			get
			{
				return this._pub_id;
			}
			set
			{
				if ((this._pub_id != value))
				{
					this._pub_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pub_name", DbType="VarChar(255)")]
		public string pub_name
		{
			get
			{
				return this._pub_name;
			}
			set
			{
				if ((this._pub_name != value))
				{
					this._pub_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pub_address", DbType="VarChar(255)")]
		public string pub_address
		{
			get
			{
				return this._pub_address;
			}
			set
			{
				if ((this._pub_address != value))
				{
					this._pub_address = value;
				}
			}
		}
	}
	
	public partial class selectPublisherByIdResult
	{
		
		private int _pub_id;
		
		private string _pub_name;
		
		private string _pub_address;
		
		public selectPublisherByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pub_id", DbType="Int NOT NULL")]
		public int pub_id
		{
			get
			{
				return this._pub_id;
			}
			set
			{
				if ((this._pub_id != value))
				{
					this._pub_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pub_name", DbType="VarChar(255)")]
		public string pub_name
		{
			get
			{
				return this._pub_name;
			}
			set
			{
				if ((this._pub_name != value))
				{
					this._pub_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pub_address", DbType="VarChar(255)")]
		public string pub_address
		{
			get
			{
				return this._pub_address;
			}
			set
			{
				if ((this._pub_address != value))
				{
					this._pub_address = value;
				}
			}
		}
	}
	
	public partial class selectAllMembersResult
	{
		
		private int _mem_id;
		
		private string _mem_name;
		
		private string _mem_address;
		
		private System.Nullable<System.DateTime> _mem_subscribe_date;
		
		private System.Nullable<System.DateTime> _mem_expiry_date;
		
		public selectAllMembersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_id", DbType="Int NOT NULL")]
		public int mem_id
		{
			get
			{
				return this._mem_id;
			}
			set
			{
				if ((this._mem_id != value))
				{
					this._mem_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_name", DbType="VarChar(255)")]
		public string mem_name
		{
			get
			{
				return this._mem_name;
			}
			set
			{
				if ((this._mem_name != value))
				{
					this._mem_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_address", DbType="VarChar(255)")]
		public string mem_address
		{
			get
			{
				return this._mem_address;
			}
			set
			{
				if ((this._mem_address != value))
				{
					this._mem_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_subscribe_date", DbType="Date")]
		public System.Nullable<System.DateTime> mem_subscribe_date
		{
			get
			{
				return this._mem_subscribe_date;
			}
			set
			{
				if ((this._mem_subscribe_date != value))
				{
					this._mem_subscribe_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_expiry_date", DbType="Date")]
		public System.Nullable<System.DateTime> mem_expiry_date
		{
			get
			{
				return this._mem_expiry_date;
			}
			set
			{
				if ((this._mem_expiry_date != value))
				{
					this._mem_expiry_date = value;
				}
			}
		}
	}
	
	public partial class selectMemberByIdResult
	{
		
		private int _mem_id;
		
		private string _mem_name;
		
		private string _mem_address;
		
		private System.Nullable<System.DateTime> _mem_subscribe_date;
		
		private System.Nullable<System.DateTime> _mem_expiry_date;
		
		public selectMemberByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_id", DbType="Int NOT NULL")]
		public int mem_id
		{
			get
			{
				return this._mem_id;
			}
			set
			{
				if ((this._mem_id != value))
				{
					this._mem_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_name", DbType="VarChar(255)")]
		public string mem_name
		{
			get
			{
				return this._mem_name;
			}
			set
			{
				if ((this._mem_name != value))
				{
					this._mem_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_address", DbType="VarChar(255)")]
		public string mem_address
		{
			get
			{
				return this._mem_address;
			}
			set
			{
				if ((this._mem_address != value))
				{
					this._mem_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_subscribe_date", DbType="Date")]
		public System.Nullable<System.DateTime> mem_subscribe_date
		{
			get
			{
				return this._mem_subscribe_date;
			}
			set
			{
				if ((this._mem_subscribe_date != value))
				{
					this._mem_subscribe_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mem_expiry_date", DbType="Date")]
		public System.Nullable<System.DateTime> mem_expiry_date
		{
			get
			{
				return this._mem_expiry_date;
			}
			set
			{
				if ((this._mem_expiry_date != value))
				{
					this._mem_expiry_date = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
